[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[features]
# Uses bevy to export bevy-related objects too
bevy = ["dep:bevy"]

[dependencies]
bevy = { version = "0.17.3", default-features = false, optional = true }
reqwest = "*"